Repository jenkins-x/acme, pull requests merged in 2020-11, with the labels that each got.

#2 feat: added in azure issuer configs for Azure DNS
  .lighthouse/jenkins-x/pullrequest.yaml
  charts/acme/templates/cert-manager-prod-clusterissuer.yaml
  charts/acme/templates/cert-manager-prod-issuer.yaml
  charts/acme/templates/cert-manager-staging-clusterissuer.yaml
  charts/acme/templates/cert-manager-staging-issuer.yaml
Labels: approved, size/S

#3 chore: add missing dns name
  charts/acme/templates/cert-manager-prod-certificate.yaml
  charts/acme/templates/cert-manager-staging-certificate.yaml
Labels: approved, size/XS

#4 fix: set azure issuer config back to 0.13 compliant values
  charts/acme/templates/cert-manager-prod-clusterissuer.yaml
  charts/acme/templates/cert-manager-prod-issuer.yaml
  charts/acme/templates/cert-manager-staging-clusterissuer.yaml
  charts/acme/templates/cert-manager-staging-issuer.yaml
Labels: approved, lgtm, ok-to-test, size/XS
